# Generated by Django 4.2.4 on 2023-08-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("faculty", "0001_initial"),
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="faculty",
            field=models.ManyToManyField(related_name="courses", to="faculty.faculty"),
        ),
    ]
